### PR TITLE
Update to Swift 5

### PR DESCRIPTION
**Pull request by kevnm67**
## Pull request checklist

- [x] All tests pass. 
- [x] Demo project builds and runs.
- [x] I have resolved merge conflicts.
- [x] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines) and [contributing guidelines](https://github.com/jessesquires/HowToContribute).

#### This fixes issue #
Closes issue #117 

## What's in this pull request?
- Migrates project settings and code for swift 5 compatibility

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks so much @kevnm67 !

Super sorry for the delay here. I'll get to this tomorrow. 😄

**Comment by jessesquires** [comment]
Reverted some of the unrelated changes that I'll take care of on `develop` instead. 😄

**Comment by kevnm67** [comment]
@jessesquires I would have happily broke out the CI updates 😆   Only reason I added them was the need to fix Travis build failures.  I actually have an Xcode 11 PR waiting 😉 
- Need to fix [one failure due to pod lint](https://github.com/kevnm67/JSQDataSourcesKit/pull/5/checks) and it should be ready to go.

**Comment by jessesquires** [comment]
@kevnm67 oops! Sorry 😅 I should have asked first

**Comment by jessesquires** [comment]
the travis config was also set to Xcode10.2, so a bit out-dated.

merged into a new branch `xcode11-swift5-1` and will be pushing updates there now 😄

**Comment by kevnm67** [comment]
@jessesquires All good.  Im all for the divide and conquer approach 😉

**Pull request merged**
