### PR TITLE
Fix codecov.yml

### PR DESCRIPTION
**Pull request by broadwaylamb**
## What's in this pull request?

Codecov does not work properly because it needs `codecov.yml` file, not `.codecov.yml`.
Coverage results are too hight because Codecov takes in account coverage of test files, which is wrong.

After renaming it should work fine.

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks @broadwaylamb ! 😄 

> Codecov does not work properly because it needs codecov.yml file, not .codecov.yml.

Not according to [their docs](https://codecov.io/docs#configuration). And you can see this change had no effect [here](https://codecov.io/gh/jessesquires/JSQDataSourcesKit/commits).

> Coverage results are too hight because Codecov takes in account coverage of test files, which is wrong.

Right, the tests are currently [ignored](https://github.com/jessesquires/JSQDataSourcesKit/blob/develop/.codecov.yml#L9), but that doesn't seem to be working. 

I haven't had time to investigate if this is a @codecov-io issue, or a problem with our config. If you find out though, please let me know! 😄

**Comment by jessesquires** [comment]
Ugh. Looks like the format for the `.yml` has changed again

**Comment by broadwaylamb** [comment]
@jessesquires perhaps that's the case, because in one of my projects it works as expected.

**Comment by jessesquires** [comment]
should be fixed by eb63e9a05c5991146224a0b737c20ca5dd7ad130

**Comment by jessesquires** [comment]
thanks for bringing this up! 👍

**Comment by broadwaylamb** [comment]
@jessesquires here's what my file looks like:

``` yaml
comment:
  layout: header, changes, diff, sunburst

coverage:
  precision: 0
  round: down
  range: "30...80"
  ignore:
  - Tests/*
  status:
    patch:
      default:
        target: auto
    project:
      default:
        target: auto
```

So `status` section in inside of `coverage` section.

Also it seems to me that this mask `Tests/.*` will affect nothing but files beginning with `.` :)

**Comment by jessesquires** [comment]
Yeah, according to the most recent codecov examples, it looks like `coverage: ignore:` has been replaced by `flags: ignore:`. 

Honestly not 100% sure. Their docs are pretty terrible.



When travis-ci finishes, we'll see 😅

**Comment by broadwaylamb** [comment]
I've just validated `.codecov.yml` in eb63e9a using
`curl -X POST -d @codecov.yml https://codecov.io/validate`.

Here's what I got:

```
Invalid value {'coverage': {'range': '60...100', 'precision': 2, 'round': 'nearest'}, 'flags': {'default': {'ignore': ['Tests/.*']}}, 'status': {'project': {'default': {'threshold': 2.0, 'branches': ['master', 'develop'], 'target': 'auto'}, 'patch': {'default': {'branches': ['master', 'develop'], 'target': 'auto'}}}}, 'comment': {'layout': 'header, diff, changes, sunburst, uncovered', 'behavior': 'default', 'branches': ['master', 'develop']}, 'codecov': {'branch': 'develop'}} (dict): additional properties: ['flags', 'status']
```

Maybe check out `https://codecov.io/gh/ACCOUNT/REPO/settings/yaml` instead of the docs? :) Like I said, worked for me.

**Comment by broadwaylamb** [comment]
@jessesquires please try this. I've validated it, it definitely should be OK.

``` yaml
codecov:
  branch: develop
coverage:
  precision: 2
  round: nearest
  range: "60...100"
  ignore: 
      - Tests/*
  status:
    project:
      default:
        target: auto
        threshold: 2.0
        branches:
        - master
        - develop
    patch:
      default:
        target: auto


comment:
  layout: "header, diff, changes, sunburst, uncovered"
  branches:
  - master
  - develop
  behavior: default
```

**Comment by jessesquires** [comment]
haha 😄 same here.

thanks @broadwaylamb ! 🎉 

i didn't know the validation API was a thing 👍

**Pull request closed without merging**
