### PR TITLE
#122 Added danger rule for milestones

### PR DESCRIPTION
**Pull request by kevnm67**
## Pull request checklist

- [x] All tests pass. 
- [x] Demo project builds and runs.
- [x] I have resolved merge conflicts.
- [x] I have followed the [coding style](https://github.com/jessesquires/HowToContribute#style-guidelines) and [contributing guidelines](https://github.com/jessesquires/HowToContribute).

#### This fixes issue #
#122 

## What's in this pull request?
- Added danger rule for milestones.

### CODE REVIEW

**Review by jessesquires — APPROVED** [review]
💯 🎉 

thanks @kevnm67 ! looks great

**Comment by jessesquires** [comment]
Looks like travis might be upset about xcpretty...

**Comment by jessesquires** [comment]
fixed the xcpretty issue at #125 

this all looks good, so going to merge now. will open PRs after to test/verify everything with danger is working

**Comment by kevnm67** [comment]
@jessesquires Sounds good.  Looks like you fixed the issue with xcpretty, nice work!  Travis can be a grumpy old man/woman/person/machine sometimes ;)

**Pull request merged**
